### ISSUE TITLE
Feature Request: Add biometrics and password box to lock work profiles

### ISSUE THREAD

**Issue by daedroza** [oasisfeng/island#261]
Hi,
Is it possible to have features such as fingerprint scanner and password to open work profiles apps?
Currently my Galaxy Launcher creates a new section called Work so I am not sure if integration would be possible.

Thanks!

**Comment by Paskalo94** [comment]
Same here, I also have a samsung phone and it creates another tab called work that anyone can access I really wish it was possible to lock it somehow.
![Screenshot_20211119-164154_One UI Home](https://user-images.githubusercontent.com/61161746/142695222-73e3b46b-c0a1-4913-971e-ce17c77cf4e7.jpg)

**Comment by Draxxx** [comment]
Yes please. Pixel user here. Would love the ability to lock work profile with biometrics.

**Comment by daedroza** [comment]
Closing the issue, I do not believe it is possible to add it external launcher. Perhaps using a different user separate from main user is the only way to do thsis.

**Comment by CodElixer** [comment]
> Closing the issue, I do not believe it is possible to add it external launcher. Perhaps using a different user separate from main user is the only way to do thsis.

Hi,
 
I have cloned some banking apps using Island and now I have those banking apps working in Work Profile but the problem is that those cloned apps are not able to find the device that this device is having the Fingerprint scanner! 
So, Is there any way to enable the Fingerprint unlock for Work Profile app as well?

Even though I have enabled the "Use one lock" feature under Work profile security settings option on Pixel 6 Pro but still the fingerprint/face unlock is not working in Island's apps(work profile apps).![Screenshot_20230418-164649_Settings.png](https://user-images.githubusercontent.com/40817467/232761393-81a51238-ea29-4575-8d6c-1b572c8d760a.png)
