### ISSUE TITLE
Island is no longer on the play store?

### ISSUE THREAD

**Issue by Xeravax** [oasisfeng/island#432]
https://play.google.com/store/apps/details?id=com.oasisfeng.island&hl=en_GB 
![image](https://github.com/oasisfeng/island/assets/25939526/fcc54777-94c7-4f01-b0f8-0ca1066dcdd3)

**Comment by supersupatcher** [comment]
Dear Developer.

Island has been removed from playstore ..it is available in github, but the version available in github is very old...can you update latest on github..

**Comment by oasisfeng** [comment]
Google pulled Island from Play Store because they decided that Island is not allowed to use `REQUEST_INSTALL_PACKAGES` permission. Actually that permission is essential for Island to clone arbitrary apps (not just the ones installed by Google Play Store). I also submitted a appeal but was rejected by Google Play team.

I'm working on a complex solution to workaround this situation, but they refuse to give me more time. When this solution is ready, Island should be qualified to be back on Google Play Store, but with limited functionality. You can install an Extension Pack from GitHub to bring back the limited functionality to the Google Play version of Island.

**Comment by oasisfeng** [comment]
> Dear Developer.
> 
> Island has been removed from playstore ..it is available in github, but the version available in github is very old...can you update latest on github..

The releases on GitHub is always up-to-date as the Google Play version. It's even days earlier because the Google Play Store has a review procedure to approve every update.

**Comment by Xeravax** [comment]
> Google pulled Island from Play Store because they decided that Island is not allowed to use `REQUEST_INSTALL_PACKAGES` permission. Actually that permission is essential for Island to clone arbitrary apps (not just the ones installed by Google Play Store). I also submitted a appeal but was rejected by Google Play team.

Google provides a function, then doesn't allow places to use it. Lmfao, LET ME INSTALL/CLONE AN APK if I WANT TO!!!

**Comment by supersupatcher** [comment]
> > Dear Developer.
> > 
> > Island has been removed from playstore ..it is available in github, but the version available in github is very old...can you update latest on github..
> 
> The releases on GitHub is always up-to-date as the Google Play version. It's even days earlier because the Google Play Store has a review procedure to approve every update.

Thank You.
Now i found.. actually from outside it was showing old.
 version...![Screenshot_2023-08-16-22-18-18-60_1ed61f9b22eb550f606d96180a328dfb.jpg](https://github.com/oasisfeng/island/assets/60211789/1f62987b-f290-495a-ae19-5519dbdab8a4)

**Comment by oasisfeng** [comment]
New release is now back on Google Play Store, currently in test channel.

**Comment by supersupatcher** [comment]
> New release is now back on Google Play Store, currently in test channel.

Dear Developer,
Can you please explain the difference between playstore version & github version..
What functionality differs.
